# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
	os = "bento/centos-7"
	config.vm.provider "hyperv"
	config.vm.box = "#{os}"
	config.vm.hostname = "tcentos02"
	config.vm.synced_folder ".", "/vagrant", disabled: true
	config.vm.network "public_network",
    use_dhcp_assigned_default_route: true

end
