domain-name:
    columbusrad.local
domain-join-username:
    svcDomJoin
domain-join-password:
    sn75YXzYiJ9A3KS1AAIV
domain-time-server:
    192.168.190.10
domain-join-target-ou:
    OU=Servers,OU=Administrative,OU=CRC,DC=ColumbusRad,DC=local